import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import matter from 'gray-matter'

const __dirname = dirname(fileURLToPath(import.meta.url))
const postsDir = join(__dirname, '../content/posts')
const outputDir = join(__dirname, '../src/generated')
const outputPath = join(outputDir, 'posts.ts')

if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true })

const posts = existsSync(postsDir)
  ? readdirSync(postsDir)
      .filter((f) => f.endsWith('.mdx'))
      .map((filename) => {
        const slug = filename.replace(/\.mdx$/, '')
        const raw = readFileSync(join(postsDir, filename), 'utf-8')
        const { data, content } = matter(raw)
        return { slug, meta: data, content }
      })
      .sort((a, b) => new Date(b.meta.date).getTime() - new Date(a.meta.date).getTime())
  : []

writeFileSync(
  outputPath,
  `// Auto-generated by scripts/generate-posts.mjs — do not edit manually
export interface PostEntry {
  slug: string
  meta: Record<string, unknown>
  content: string
}

export const posts: PostEntry[] = ${JSON.stringify(posts, null, 2)}
`,
)

console.log(`Generated ${posts.length} post(s) → src/generated/posts.ts`)
